apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportive-message-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supportive-message-consumer
  template:
    metadata:
      labels:
        app: supportive-message-consumer
    spec:
      containers:
        - name: supportive-message-consumer
          image: ghcr.io/drxxmn/supportive-message-consumer:main
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=postgresql.default.svc.cluster.local;Database=messagesdb;User Id=postgres;Password=password;"
            - name: RabbitMQ__Host
              value: "rabbitmq.default.svc.cluster.local"
            - name: RabbitMQ__QueueName
              value: "supportive_messages"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: supportive-message-consumer
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: supportive-message-consumer
