version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  moodtrackerapi:
    build:
      context: .
      dockerfile: MoodTrackerAPI/Dockerfile
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MongoDB__ConnectionString: "mongodb://admin:secret@mongodb:27017"
      MongoDB__DatabaseName: "MoodTrackerProd"
    ports:
      - "8000:8080"

volumes:
  mongodb_data:
