apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: moodtracker-route
spec:
  parentRefs:
    - name: envoy-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - group: ""
          kind: Service
          name: moodtrackerapi
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /SupportiveMessage
      backendRefs:
        - group: ""
          kind: Service
          name: supportive-message-producer
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /SupportiveMessageService
      backendRefs:
        - group: ""
          kind: Service
          name: supportive-message-service
          port: 8080
