version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  moodtrackerapi:
    build:
      context: .
      dockerfile: MoodTrackerAPI/Dockerfile
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8000:80"

volumes:
  mongodb_data_container:
