apiVersion: v1
kind: Service
metadata:
  name: mongo-config-service
  labels:
    app: mongo
    component: config-server
spec:
  ports:
    - port: 27019
  clusterIP: None
  selector:
    app: mongo
    component: config-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-config-server
spec:
  serviceName: "mongo-config-service"
  replicas: 3
  selector:
    matchLabels:
      app: mongo
      component: config-server
  template:
    metadata:
      labels:
        app: mongo
        component: config-server
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.29
          command:
            - mongod
            - "--configsvr"
            - "--replSet"
            - "configReplSet"
            - "--bind_ip_all"
          ports:
            - containerPort: 27019
          volumeMounts:
            - name: mongo-config-server-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-config-server-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
