apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-shard-server
  labels:
    app: mongo
    component: shard-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
      component: shard-server
  template:
    metadata:
      labels:
        app: mongo
        component: shard-server
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          command: ["mongod", "--shardsvr", "--replSet", "shardReplSet", "--bind_ip_all"]
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard-service
  labels:
    app: mongo
    component: shard-server
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    app: mongo
    component: shard-server
