apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-query-router
  labels:
    app: mongo
    component: query-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      component: query-router
  template:
    metadata:
      labels:
        app: mongo
        component: query-router
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          command:
            [
              "mongos",
              "--configdb",
              "configReplSet/mongo-config-service:27017",
              "--bind_ip_all"
            ]
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-query-router-service
  labels:
    app: mongo
    component: query-router
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
    component: query-router
