apiVersion: v1
kind: Service
metadata:
  name: mongo-query-router-service
  labels:
    app: mongo
    component: query-router
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
    component: query-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-query-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      component: query-router
  template:
    metadata:
      labels:
        app: mongo
        component: query-router
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.29
          command:
            - mongos
            - "--configdb"
            - "configReplSet/mongo-config-server-0.mongo-config-service.default.svc.cluster.local:27019,mongo-config-server-1.mongo-config-service.default.svc.cluster.local:27019,mongo-config-server-2.mongo-config-service.default.svc.cluster.local:27019"
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
