name: .NET CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'MoodTrackerAPI/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'MoodTrackerAPI/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup .NET, Build, Test, and Publish

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t ghcr.io/drxxmn/sentimate-api:latest -f MoodTrackerAPI/Dockerfile .
          docker push ghcr.io/drxxmn/sentimate-api:latest

      # Azure Login and Deployment
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B60080F9102E4CA3A1F3768F41290C58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_28E4A71A8594460DB608C78F0533EEA0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4051A066ECA2479B889957E736F00276 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sentimate-api'
          images: 'ghcr.io/drxxmn/sentimate-api:latest'
