name: .NET CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'Services/MoodTrackerAPI/**'
  pull_request:
    branches: [main]
    paths:
      - 'Services/MoodTrackerAPI/**'

  
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Services/MoodTrackerAPI
          file: ./Services/MoodTrackerAPI/Dockerfile
          tags: ghcr.io/drxxmn/sentimate-api:latest
          push: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
