name: .NET CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'MoodTrackerAPI/**'
  pull_request:
    branches: [main]
    paths:
      - 'MoodTrackerAPI/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore MoodTrackerAPI/MoodTrackerAPI.csproj

      - name: Build
        run: dotnet build MoodTrackerAPI/MoodTrackerAPI.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test MoodTrackerAPI/MoodTrackerAPI.csproj --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish MoodTrackerAPI/MoodTrackerAPI.csproj -c Release -o ./publish --no-restore

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f MoodTrackerAPI/Dockerfile ./publish

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
